### ISSUE TITLE
Error: L.MarkerCluster not an object (Right-hand side of 'instanceof' is not an object) 

### ISSUE THREAD

**Issue by kirinmurphy** [yuzhva/react-leaflet-markercluster#122]
Hi. 

I am getting this error with a map after adding `react-marker-cluster`.

Sometimes it happens on mount, sometimes it happens when I'm interacting with the map, and sometimes it happens when unmounted as I'm going to another page.   Usually it works great until I unmount the component.  

```
Uncaught TypeError: Right-hand side of 'instanceof' is not an object
    at NewClass.fire (leaflet.markercluster-src.js:801)
    at NewClass._propagateEvent (leaflet-src.js:664)
    at NewClass.fire (leaflet-src.js:601)
    at NewClass._propagateEvent (leaflet-src.js:664)
    at NewClass.fire (leaflet-src.js:601)
    at NewClass._fireDOMEvent (leaflet-src.js:4451)
    at NewClass._handleDOMEvent (leaflet-src.js:4408)
    at HTMLDivElement.handler (leaflet-src.js:2678)
```

This is the line with the thing that's not an object 
```
if (data && data.layer instanceof L.MarkerCluster) {
```

Here's my component instance
```
  const allLatLongs = markers.map(marker => marker.position);
  return (
    <div className="map">
      <Map bounds={allLatLongs}>
        <TileLayer
          attribution='&amp;copy <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'
          url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
        />
        <MarkerClusterGroup>
          {markers.map(({ markerData, position }) => {
            return (
              <Marker position={position} key={markerData.source.id}>
                <Popup>
                  {tooltipTemplate(markerData)}
                </Popup>
              </Marker>  
            );
          })}
        </MarkerClusterGroup>
      </Map>
    </div>
  );
}
```

and here are my dependencies
```
  "dependencies": {
    "@apollo/client": "^3.2.2",
    "date-fns": "^2.11.1",
    "dotenv": "^8.2.0",
    "graphql": "^15.3.0",
    "graphql-tag": "^2.11.0",
    "gray-matter": "^4.0.2",
    "isomorphic-unfetch": "^3.0.0",
    "leaflet": "^1.6.0",
    "leaflet.markercluster": "^1.4.1",
    "next": "9.5.3",
    "next-on-netlify": "^2.5.1",
    "next-with-apollo": "^5.1.0",
    "nookies": "^2.4.0",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-hook-form": "^6.8.6",
    "react-leaflet": "^2.7.0",
    "react-leaflet-markercluster": "^2.0.0",
    "remark": "^12.0.0",
    "remark-html": "^11.0.1",
    "styled-components": "^5.2.0",
    "swr": "^0.3.7"
  }
```

It happens both in prod and locally, but locally I'm using 
NODE - v14.12.0
NPM - 6.14.8

Thanks!

**Comment by yuzhva** [comment]
Hey hi, @kirinmurphy
You faced an interesting issue...

Here what I found in `Leaflet.markercluster` issues:
https://github.com/Leaflet/Leaflet.markercluster/pull/961#issuecomment-557719266

The questions are:
- Are you using `npm` or `yarn` as a package manager?
- Do you have the `package-lock.json` or `yarn.lock` files in the project?
- In case you do, are you committing them to production?

Thanks

**Comment by kirinmurphy** [comment]
Hi @yuzhva 
Thanks for the quick feedback.  

I am using yarn, and do have the yarn.lock file in the project.  
I do commit the yarn.lock file to my repo.

**Comment by yuzhva** [comment]
@kirinmurphy Have you tried to delete `yarn.lock` and `node_modules` and reinstall dependencies from scratch?

**Comment by Lorincz** [comment]
Hi, 

Unfortunately I run into the same issue, but I am using npm and react-leaflet v3.

TypeError: Right-hand side of 'instanceof' is not an object
NewClass.fire
src/MarkerClusterGroup.js:790
 ```
 787 | 
  788 | //Override L.Evented.fire
  789 | fire: function (type, data, propagate) {
>790 | 	if (data && data.layer instanceof L.MarkerCluster) {
      | ^  791 | 		//Prevent multiple clustermouseover/off events if the icon is made up of stacked divs (Doesn't work in ie <= 8, no relatedTarget)
  792 | 		if (data.originalEvent && this._isOrIsParent(data.layer._icon, data.originalEvent.relatedTarget)) {
  793 | 			return;
```

Do you have any advice on how can I solve this?

Best Regards,
Istvan

**Comment by ldelavois** [comment]
Hi!
I have the same issue and i don't know where it comes from.
Best Regards,
Ludovic

**Comment by dmmishchenko** [comment]
same for me, have such call stack
```
TypeError: Right-hand side of 'instanceof' is not an object
    at NewClass.fire (leaflet.markercluster-src.js:802:1)
    at NewClass.removeLayer (leaflet.markercluster-src.js:159:1)
```

**Comment by RobRover** [comment]
Same error...

**Comment by AbhaysinghBhosale** [comment]
Same error in 2026
