### ISSUE TITLE
MarkerClusterGroup is not workable with latest version of react-leaflet

### ISSUE THREAD

**Issue by vyemialyanchyk** [yuzhva/react-leaflet-markercluster#170]
'No context provided: useLeafletContext() can only be used in a descendant of <MapContainer>' with latest version of react-leaflet

**Comment by vyemialyanchyk** [comment]
```
Uncaught Error: No context provided: useLeafletContext() can only be used in a descendant of <MapContainer>
    at useLeafletContext (:3000/static/js/vendors~main.chunk.js:467)
    at usePath (:3000/static/js/vendors~main.chunk.js:981)
    at ContainerComponent (:3000/static/js/vendors~main.chunk.js:402)
    at renderWithHooks (:3000/static/js/vendors~main.chunk.js:104109)
    at updateForwardRef (:3000/static/js/vendors~main.chunk.js:106131)
    at beginWork (:3000/static/js/vendors~main.chunk.js:108119)
    at HTMLUnknownElement.callCallback (:3000/static/js/vendors~main.chunk.js:93059)
    at Object.invokeGuardedCallbackDev (:3000/static/js/vendors~main.chunk.js:93108)
    at invokeGuardedCallback (:3000/static/js/vendors~main.chunk.js:93168)
    at beginWork$1 (:3000/static/js/vendors~main.chunk.js:112910)
    at performUnitOfWork (:3000/static/js/vendors~main.chunk.js:111746)
    at workLoopSync (:3000/static/js/vendors~main.chunk.js:111683)
    at renderRootSync (:3000/static/js/vendors~main.chunk.js:111649)
    at performSyncWorkOnRoot (:3000/static/js/vendors~main.chunk.js:111266)
    at :3000/static/js/vendors~main.chunk.js:100519
    at unstable_runWithPriority (:3000/static/js/vendors~main.chunk.js:129997)
    at runWithPriority$1 (:3000/static/js/vendors~main.chunk.js:100465)
    at flushSyncCallbackQueueImpl (:3000/static/js/vendors~main.chunk.js:100514)
    at flushSyncCallbackQueue (:3000/static/js/vendors~main.chunk.js:100502)
    at flushPassiveEffectsImpl (:3000/static/js/vendors~main.chunk.js:112569)
    at unstable_runWithPriority (:3000/static/js/vendors~main.chunk.js:129997)
    at runWithPriority$1 (:3000/static/js/vendors~main.chunk.js:100465)
    at flushPassiveEffects (:3000/static/js/vendors~main.chunk.js:112402)
    at flushDiscreteUpdates (:3000/static/js/vendors~main.chunk.js:111329)
    at flushDiscreteUpdatesIfNeeded (:3000/static/js/vendors~main.chunk.js:92882)
    at dispatchDiscreteEvent (:3000/static/js/vendors~main.chunk.js:95049)
index.js:1350 The above error occurred in the <ForwardRef(ContainerComponent)> component:

    at ContainerComponent (http://localhost:3000/static/js/vendors~main.chunk.js:402:9)
    at div
    at MapContainer (http://localhost:3000/static/js/vendors~main.chunk.js:118149:5)
    at div

```

**Comment by vyemialyanchyk** [comment]
```
		"leaflet": "1.7.1",
		"leaflet.markercluster": "1.5.3",
		"react-leaflet": "3.2.2",
		"react-leaflet-markercluster": "3.0.0-rc1",

```

**Comment by jaballogian** [comment]
I also found this issue but with a different error message and a different `react-leaflet` version here https://codesandbox.io/s/github-leaflet-marker-cluster-bug-6nur7s

**Comment by ayalpani** [comment]
Hi @jaballogian 

I have the exakt same configuration and the same error message. What did you do about it in the end?
Cheers

**Comment by jaballogian** [comment]
> Hi @jaballogian
> 
> I have the exakt same configuration and the same error message. What did you do about it in the end? Cheers

Hello @ayalpani 
Sadly, I still use `react` v17 and `react-leaflet` v3 now
In the future, if this library has supported `react` v18 and `react-leaflet` v4, I would try to update all the dependencies

**Comment by ayalpani** [comment]
Thanks @jaballogian for your quick response. I will have to stick with React 17 then too for the moment
