### ISSUE TITLE
v4.1.2: is it real?

### ISSUE THREAD

**Issue by barbalex** [yuzhva/react-leaflet-markercluster#216]
According to npm there seems to be a new version: 4.1.2: https://www.npmjs.com/package/react-leaflet-markercluster?activeTab=versions

Or not?

It is not listed on the releases on github: https://github.com/yuzhva/react-leaflet-markercluster/releases

And after installing it, I got this error: 

```console
Error:   Failed to scan for dependencies from entries:
  C:/Users/alexa/apf2/index.html
C:/Users/alexa/apf2/playwright-report/index.html

  X [ERROR] Missing "./dist/styles.min.css" specifier in "react-leaflet-markercluster" package [plugin vite:dep-scan]

    src/App.jsx:19:7:
      19 │ import 'react-leaflet-markercluster/dist/styles.min.css'
         ╵        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  This error came from the "onResolve" callback registered here:

    node_modules/vite/node_modules/esbuild/lib/main.js:1150:20:
      1150 │       let promise = setup({
           ╵                     ^

    at setup (file:///C:/Users/alexa/apf2/node_modules/vite/dist/node/chunks/dep-yUJfKD1i.js:18162:13)
    at handlePlugins (C:\Users\alexa\apf2\node_modules\vite\node_modules\esbuild\lib\main.js:1150:21)
    at buildOrContextImpl (C:\Users\alexa\apf2\node_modules\vite\node_modules\esbuild\lib\main.js:873:5)
    at Object.buildOrContext (C:\Users\alexa\apf2\node_modules\vite\node_modules\esbuild\lib\main.js:699:5)
    at C:\Users\alexa\apf2\node_modules\vite\node_modules\esbuild\lib\main.js:2037:68
    at new Promise (<anonymous>)
    at Object.context (C:\Users\alexa\apf2\node_modules\vite\node_modules\esbuild\lib\main.js:2037:27)
    at Object.context (C:\Users\alexa\apf2\node_modules\vite\node_modules\esbuild\lib\main.js:1879:58)
    at prepareEsbuildScanner (file:///C:/Users/alexa/apf2/node_modules/vite/dist/node/chunks/dep-yUJfKD1i.js:17947:24)


    at failureErrorWithLog (C:\Users\alexa\apf2\node_modules\vite\node_modules\esbuild\lib\main.js:1476:15)
    at C:\Users\alexa\apf2\node_modules\vite\node_modules\esbuild\lib\main.js:945:25
    at runOnEndCallbacks (C:\Users\alexa\apf2\node_modules\vite\node_modules\esbuild\lib\main.js:1316:45)
    at buildResponseToResult (C:\Users\alexa\apf2\node_modules\vite\node_modules\esbuild\lib\main.js:943:7)
    at C:\Users\alexa\apf2\node_modules\vite\node_modules\esbuild\lib\main.js:955:9
    at new Promise (<anonymous>)
    at requestCallbacks.on-end (C:\Users\alexa\apf2\node_modules\vite\node_modules\esbuild\lib\main.js:954:54)
    at handleRequest (C:\Users\alexa\apf2\node_modules\vite\node_modules\esbuild\lib\main.js:647:17)
    at handleIncomingPacket (C:\Users\alexa\apf2\node_modules\vite\node_modules\esbuild\lib\main.js:672:7)
    at Socket.readFromStdout (C:\Users\alexa\apf2\node_modules\vite\node_modules\esbuild\lib\main.js:600:7)
```

**Comment by charlieforward9** [comment]
@barbalex yes it is real, it is a release that should support ESM, at least on my machine. 

I will take a look at this error report and try to get it resolved as quickly as possible. For now, please stick with `4.1.1`

**Comment by charlieforward9** [comment]
Since `4.1.2`, refactor the styles import as such: 

```diff
-import 'react-leaflet-markercluster/dist/styles.min.css'
+import "react-leaflet-markercluster/styles";
```

**Comment by barbalex** [comment]
Works! Thanks so much for providing us this great tool.
